[package]
name = "utils"
version = "0.1.0"
authors = ["cmeinco <trent@appsec.wtf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-colors = "3.5.0"
loggy = "^0.5.2"
log = "^0.4.17"
env_logger = "0.9.0"